### ISSUE TITLE
Incorrectly decoded packets in pcap_agent

### ISSUE THREAD

**Issue by m3047** [m3047/shodohflo#6]
I'm seeing this sporadically:
```
  ERROR:asyncio:Exception in callback Server.process_data()
   handle: <Handle Server.process_data()>
   Traceback (most recent call last):
     File "/usr/lib64/python3.6/asyncio/events.py", line 145, in _run
       self._callback(*self._args)
     File "/usr/local/share/shodohflo/agents/pcap_agent.py", line 315, in process_data
       if pkt.p == socket.IPPROTO_TCP and pkt.data.flags & dpkt.tcp.TH_RST:
   AttributeError: 'bytes' object has no attribute 'flags'
```
and I'm adding some code to the `fwm` branch to assess how often it's occurring and test a possible mitigation.

**Comment by m3047** [comment]
My instrumentation reveals the following:

    INFO:root:Packet Types: IP.TCP=993414 IP.bytes=2

This tells me that in rare circumstances the TCP payload can't be decoded. For my purposes ignoring those cases is sufficient mitigation. Speak up if you disagree...
